// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seoxttvilirxgcexnlcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlb3h0dHZpbGlyeGdjZXhubGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTQxMjYsImV4cCI6MjA2NzA3MDEyNn0.LPrKOW7ehaSZfbmzLcTisFvs5K12M3hY0plrwzVFj3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});